# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the custom index.html file into the Nginx HTML directory
COPY ./index.html /usr/share/nginx/html/index.html

# Expose port 80 for HTTP traffic
EXPOSE 80

